#!/usr/bin/env python3
"""Generate and measure an isolated synthetic vault; publish only verified 10k observations."""
import argparse
from contextlib import contextmanager
import hashlib
import json
import math
import os
from pathlib import Path
import platform
import shutil
import socket
import stat
import statistics
import subprocess
import time
import urllib.request
import uuid

from vault import DEFAULT_COUNT, directory_fd, ensure_directory, generate, payload, read_regular, specimen, write_owned

ROOT = Path(__file__).resolve().parents[2]
DESIGNATED = Path.home() / ".cache/lysilogy/bench-vault"
COLLECTOR = "eval/inputs/scale/synthetic-vault.json"
EVIDENCE = "eval/inputs/evidence/synthetic-vault"


def designated_root(value):
    value = Path(value).expanduser().absolute()
    if not value.is_relative_to(DESIGNATED) or ".." in value.parts:
        raise ValueError("benchmark PDFs and run data must stay under ~/.cache/lysilogy/bench-vault/")
    for component in [*value.parents, value]:
        if component.is_symlink():
            raise ValueError("benchmark root must not traverse symlinks")
    return value


def verify_vault(root):
    """Verify exact generated bytes and reject extra files, missing files, and symlinks."""
    manifest = json.loads(read_regular(root / "manifest.json"))
    config = json.loads(read_regular(root / "generation.json"))
    if config != {key: manifest[key] for key in ("schema_version", "count", "seed")}:
        raise ValueError("manifest differs from generation config")
    if config["schema_version"] != 1 or not 1 <= config["count"] <= DEFAULT_COUNT:
        raise ValueError("invalid generation config")
    if len(manifest["papers"]) != config["count"]:
        raise ValueError("manifest paper count differs")
    expected = set()
    for index, row in enumerate(manifest["papers"]):
        relative, pdf, metadata = specimen(config["seed"], index)
        expected.add(relative)
        if row != dict(path=relative, sha256=hashlib.sha256(pdf).hexdigest(), bytes=len(pdf), metadata=metadata):
            raise ValueError("manifest is not the deterministic synthetic truth")
        path = root / "papers" / relative
        if read_regular(path, len(pdf)) != pdf:
            raise ValueError("generated PDF differs from truth")
    actual = set()
    with directory_fd(root / "papers") as descriptor:
        for directory, directories, files, current in os.fwalk(".", dir_fd=descriptor, follow_symlinks=False):
            if any(stat.S_ISLNK(os.stat(name, dir_fd=current, follow_symlinks=False).st_mode) for name in directories + files):
                raise ValueError("symlink in generated papers")
            actual.update(str(Path(directory) / name) for name in files)
    if expected != actual:
        raise ValueError("generated vault contains extra or missing files")
    return manifest


def atomic_json(path, value):
    write_owned(path, payload(value), replace=True)


def evidence(path, version="synthetic-benchmark-v1"):
    return dict(path=path, sha256=hashlib.sha256((ROOT / path).read_bytes()).hexdigest(), version=version)


def implementation():
    paths = {"Cargo.toml", "Cargo.lock", "web/package.json", "web/package-lock.json",
             "web/vite.config.ts", "web/index.html", "examples/scale_bench.rs"}
    for prefix in ("src", "web/src", "scripts/bench"):
        for directory, directories, files in os.walk(ROOT / prefix, followlinks=False):
            directories[:] = [name for name in directories if not name.startswith('.') and name != '__pycache__']
            for name in files:
                file = Path(directory) / name
                if not name.startswith('.') and file.suffix in (".rs", ".py", ".ts", ".tsx", ".css") and not file.is_symlink():
                    paths.add(str(file.relative_to(ROOT)))
    paths.add("web/scripts/scale-bench.mjs")
    return [evidence(path) for path in sorted(paths)]


def report(metadata, run_directory):
    """A derived Markdown report; measured results never imply an eval gate pass."""
    summary = metadata["summary"]
    rows = [(key, value) for key, value in summary.items() if key != "O27"]
    return ("# Synthetic 10k benchmark\n\n"
            f"Source `{metadata['commit']}`, dirty: `{metadata['dirty']}`; release backend.\n\n"
            f"Machine: {metadata['machine']}; CPUs: {metadata['cpu_count']}.\n\n"
            f"Manifest SHA-256: `{metadata['manifest_sha256']}`.\n\n"
            f"Retained observations/artifacts: `{run_directory}`.\n\n"
            "| Measurement | Value |\n| --- | --- |\n"
            + "".join(f"| {key} | {value} |\n" for key, value in rows)
            + f"\nModel cost: $0. Total wall time including setup/builds: {metadata['wall_seconds']:.3f} s.\n\n"
            "O25 uses all 10,000 persisted extraction artifacts; O26 uses three fresh browser contexts. "
            "O27 remains unavailable because experimental extractor capacity does not measure production ingest concurrency. "
            "Run `lysilogy eval scale --check` for gate/ratchet assessment; no threshold was relaxed.\n")


def positive(values):
    if not values or any(not isinstance(value, (float, int)) or not math.isfinite(value) or value <= 0 for value in values):
        raise ValueError("phase requires finite positive measured timings")
    return values


def summarize(backend, browser, count):
    if backend["papers"] != count or browser["papers"] != count:
        raise ValueError("phase counts differ from verified vault")
    initial = positive([backend["catalog_initial_seconds"]])[0]
    rescans = positive(backend["catalog_populated_no_change_seconds"])
    discovered = positive(backend["catalog_discovered_no_change_seconds"])
    if backend["populated_papers"] != count:
        raise ValueError("populated rescan must cover every paper's actual extraction artifact")
    population = positive([backend["population_seconds"]])[0]
    populated_initial = positive([backend["catalog_populated_initial_seconds"]])[0]
    home = positive(browser["home_first_render_ms"])
    searches = positive([row["milliseconds"] for row in browser["search"]])
    batches = backend["extraction"]
    if not batches or len({batch["output_sha256"] for batch in batches}) != 1:
        raise ValueError("extraction output hashes differ")
    if len({batch["papers"] for batch in batches}) != 1 or not 1 <= batches[0]["papers"] <= count:
        raise ValueError("extraction trials have different populations")
    serial = statistics.median(positive([batch["seconds"] for batch in batches if batch["workers"] == 1]))
    parallel = statistics.median(positive([batch["seconds"] for batch in batches if batch["workers"] == 4]))
    return dict(catalog_initial_seconds=initial, catalog_populated_no_change_median_seconds=statistics.median(rescans),
                catalog_discovered_no_change_median_seconds=statistics.median(discovered),
                population_seconds=population, populated_papers=count,
                catalog_populated_initial_seconds=populated_initial,
                home_first_render_median_ms=statistics.median(home),
                search_p95_ms=sorted(searches)[math.ceil(len(searches) * .95) - 1],
                extraction_papers=batches[0]["papers"], serial_median_seconds=serial,
                four_worker_median_seconds=parallel, extractor_parallel_efficiency=serial / parallel / 4,
                production_ingest_workers=backend["production_ingest_workers"],
                O27="unavailable: benchmark-only scheduler is not the production ingest path")


def publish(manifest, backend, browser, provenance, wall_seconds, metadata=None):
    summary = summarize(backend, browser, manifest["count"])
    if manifest["count"] != DEFAULT_COUNT:
        raise ValueError("only a complete 10000-paper run can publish scale metrics")
    if len(backend["catalog_populated_no_change_seconds"]) < 3 or len(browser["home_first_render_ms"]) < 3 or len(browser["search"]) < 20:
        raise ValueError("scale publication requires three rescans, three navigations, and at least twenty searches")
    if provenance != implementation():
        raise ValueError("implementation changed during benchmark; rerun before publishing")
    truth_path, trace_path = f"{EVIDENCE}/manifest.json", f"{EVIDENCE}/observations.json"
    atomic_json(ROOT / truth_path, manifest)
    atomic_json(ROOT / trace_path, dict(backend=backend, browser=browser, summary=summary, run=metadata))
    trace = [evidence(trace_path)]
    metrics = {
        "O25": dict(sample=dict(method="median", values=backend["catalog_populated_no_change_seconds"]), cases=DEFAULT_COUNT, evidence=trace),
        "O26.render": dict(sample=dict(method="median", values=browser["home_first_render_ms"]), cases=DEFAULT_COUNT, evidence=trace),
        "O26.search": dict(sample=dict(method="p95", values=[row["milliseconds"] for row in browser["search"]]), cases=DEFAULT_COUNT, evidence=trace),
    }
    atomic_json(ROOT / COLLECTOR, dict(schema_version=1, suite="scale", collector="synthetic-vault-v1",
                implementation=provenance, truth_sets={"synthetic": evidence(truth_path)}, metrics=metrics,
                cost_usd=0, wall_seconds=wall_seconds))
    return summary


@contextmanager
def serve(binary, root, run, web):
    # Reserve a random loopback port, then confirm the spawned process stays alive
    # while health polling. Browser checks the exact manifest count afterward.
    with socket.socket() as reservation:
        reservation.bind(("127.0.0.1", 0))
        port = reservation.getsockname()[1]
    config = run / "config.json"
    atomic_json(config, {})
    command = [str(binary), "--library", str(root / "papers"), "--data", str(run / "catalog-data"),
               "--notes", str(run / "notes"), "--config", str(config), "serve", "--bind",
               f"127.0.0.1:{port}", "--web", str(web)]
    with (run / "server.log").open("wb") as log:
        process = subprocess.Popen(command, cwd=run, stdout=log, stderr=log)
        try:
            url = f"http://127.0.0.1:{port}"
            opener = urllib.request.build_opener(urllib.request.ProxyHandler({}))
            deadline = time.monotonic() + 180
            while True:
                if process.poll() is not None:
                    raise RuntimeError(f"isolated backend exited; see {run / 'server.log'}")
                try:
                    with opener.open(url + "/api/health", timeout=1) as response:
                        if response.status == 200:
                            break
                except OSError:
                    pass
                if time.monotonic() >= deadline:
                    raise RuntimeError("isolated backend did not become healthy")
                time.sleep(.1)
            yield url
        finally:
            process.terminate()
            try:
                process.wait(timeout=10)
            except subprocess.TimeoutExpired:
                process.kill()
                process.wait()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=DESIGNATED)
    parser.add_argument("--count", type=int, default=DEFAULT_COUNT)
    parser.add_argument("--seed", type=int, default=19)
    parser.add_argument("--repeats", type=int, default=3, choices=range(3, 21))
    parser.add_argument("--extraction-limit", type=int, default=DEFAULT_COUNT,
                        help="optional smaller extraction capacity sample; O27 remains unavailable")
    args = parser.parse_args()
    root = designated_root(args.root)
    ancestor = next(path for path in [root, *root.parents] if path.exists())
    if shutil.disk_usage(ancestor).free < 5 * 1024 ** 3:
        raise ValueError("benchmark requires at least 5 GiB free for extraction artifacts and builds")
    started = time.monotonic()
    generate(root, args.count, args.seed)
    manifest = verify_vault(root)
    # Generation and verification are excluded from phase timings. Every run is
    # retained separately; no previous artifacts or browser profile are deleted.
    run = root / "runs" / uuid.uuid4().hex
    ensure_directory(run)
    provenance = implementation()
    environment = {**os.environ, "CARGO_BUILD_JOBS": "1", "CARGO_INCREMENTAL": "0",
                   "CARGO_TARGET_DIR": str(ROOT / "target")}
    subprocess.run(["cargo", "build", "--offline", "--release", "--bin", "lysilogy", "--example", "scale_bench"],
                   cwd=ROOT, env=environment, check=True)
    subprocess.run(["npm", "run", "build"], cwd=ROOT / "web", check=True)
    command = [str(ROOT / "target/release/examples/scale_bench"), "--library", str(root / "papers"),
               "--data", str(run / "catalog-data"), "--expected-count", str(manifest["count"]),
               "--repeats", str(args.repeats), "--extraction-limit", str(args.extraction_limit)]
    backend = json.loads(subprocess.check_output(command, cwd=run, text=True))
    atomic_json(run / "backend.json", backend)
    ensure_directory(run / "browser-tmp")
    with serve(ROOT / "target/release/lysilogy", root, run, ROOT / "web/dist") as url:
        subprocess.run(["node", str(ROOT / "web/scripts/scale-bench.mjs"), url, str(manifest["count"]),
                        str(args.repeats), str(run / "browser.json"), str(run / "home.png")], check=True,
                       env={**os.environ, "TMPDIR": str(run / "browser-tmp")})
    browser = json.loads((run / "browser.json").read_text())
    verify_vault(root)
    summary = summarize(backend, browser, manifest["count"])
    if provenance != implementation():
        raise ValueError("implementation changed during benchmark; rerun before publishing")
    metadata = dict(schema_version=1, commit=subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip(),
                    dirty=bool(subprocess.check_output(["git", "status", "--porcelain"], cwd=ROOT)),
                    machine=platform.platform(), cpu_count=os.cpu_count(), build_profile="release", cost_usd=0,
                    wall_seconds=time.monotonic() - started, manifest_sha256=hashlib.sha256(payload(manifest)).hexdigest(),
                    implementation=provenance, summary=summary)
    atomic_json(run / "result.json", metadata)
    if manifest["count"] == DEFAULT_COUNT:
        publish(manifest, backend, browser, provenance, metadata["wall_seconds"], metadata)
        from datetime import date
        from vault import retain_file
        report_path = ROOT / "docs/experiment-reports" / f"{date.today()}-e0.1-{run.name[:8]}.md"
        retain_file(report_path, report(metadata, run).encode())
    print(json.dumps(dict(run=str(run), published=manifest["count"] == DEFAULT_COUNT, **summary), indent=2))


if __name__ == "__main__":
    main()
